### ISSUE TITLE
Website links to non-existant relase (mac os, arm64)

### ISSUE THREAD

**Issue by hanleybrand** [oslabs-beta/kaptn#49]
Small issue, but important to fix -- The Mac download icon on an M1 mac at https://kaptn.io/ redirects to 

https://github.com/oslabs-beta/kaptn/releases/download/V1.0.0/Kaptn-1.0.0-mac-arm64.dmg 

which does not exist -- not sure if that file is supposed to be or not, I'd assume it's a universal and the only required action is updating the website.

**Comment by jhwiwonc** [comment]
Thank you for bringing our attention to this issue. We're happy to let you know that the download icon has been fixed.
