### ISSUE TITLE
Build for Linux

### ISSUE THREAD

**Issue by Kyle-Hughes-Imprivata** [oslabs-beta/kaptn#52]
Hi,

I run exclusively Linux nowadays, especially on my dev machines (both work and personal).  As this is Electron, is it difficult to add a Linux build to your releases?

Thanks,
Kyle

**Comment by brecht-horn** [comment]
Hi thanks for your comment, we have released a linux version with the newly released v1.1.0. Please download now, thanks! 

Also please note that our team is entirely Mac users and so the linux and windows versions are untested. If you have any issues, please submit tickets, thanks!

Closing issue.
