### ISSUE TITLE
webkit-scrollbar-thumb element visible on default resolution

### ISSUE THREAD

**Issue by pythoninthegrass** [oslabs-beta/kaptn#55]
On a 2021 MacBook Pro, M1 Pro, macOS Monterey 12.6.1 (21G217) box, the `webkit-scrollbar-thumb element`is appearing on the default window size 1312 × 812. ~1405 × 919 and above work just fine.

Think if the breakpoint set at 790px was removed on the `top-bar` or `MuiGrid-*` elements that should make it go away. Not a webdev so pardon my ignorance on html vs. css root cause here.

![Screen Shot 2023-05-29 at 9 12 53 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/93345839-5647-4d87-84f2-801c11708097)
![Screen Shot 2023-05-29 at 9 12 58 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/8b90b5c0-dd48-4e57-9303-54ba504e6527)
![Screen Shot 2023-05-29 at 9 13 23 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/7e5af713-d93d-46d2-a7c2-45c4ccf8b91e)
![Screen Shot 2023-05-29 at 9 22 22 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/4fd8f3aa-1d1b-43d0-9971-0dbe7fc3afb6)
![Screen Shot 2023-05-29 at 9 23 30 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/9a826ea5-413f-4055-9f8a-2ea05a7e0120)
![Screen Shot 2023-05-29 at 9 23 34 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/26cfa4a7-09e7-42cb-83de-2a46c1c223e6)
![Screen Shot 2023-05-29 at 9 32 46 PM](https://github.com/oslabs-beta/kaptn/assets/4097471/288f349a-432c-4746-bb5a-c08168f363a9)

**Comment by brecht-horn** [comment]
Hi thanks for your comment, this has been fixed with the newly released v1.1.0. Please download now, thanks! 

Closing issue.

**Comment by brecht-horn** [comment]
Hi thanks for your comment, this has been fixed with the newly released v1.1.0. Please download now, thanks! 

Closing issue.
