### ISSUE TITLE
Kaptn.app is damaged and cant be opened

### ISSUE THREAD

**Issue by raidermike** [oslabs-beta/kaptn#61]
Apple M2 Pro, Ventura 13.4 getting a kaptn.app is damaged and cant be opened.

![image](https://github.com/oslabs-beta/kaptn/assets/13000807/29498e46-5e48-4894-83e6-a68151edfb40)

**Comment by brecht-horn** [comment]
Hi there,

Thanks very much for bringing this to our attention. After some research, this appears to be a code signing issue with Apple, and while we are working on a solution, it cannot be remedied immediately.

In the meantime as a workaround, please try the other Mac version, which should work universally on both Intel and Apple Silicon Macs.

Thank you.
